const inspirations = [
    {
        id: 1,
        roomType: 'Living Room',
        designStyle: 'Minimalist',
        title: 'Tranquility in Neutral Hues',
        description: 'Experience serenity with clean lines, neutral tones, and a clutter-free living space.',
        imageUrl: '/images/minimalist-living-room1.jpg',
        altText: 'A living and dining room with natural light and indoor plants ',
    },
    {
        id: 2,
        roomType: 'Bedroom',
        designStyle: 'Bohemian',
        title: 'The Artistic Haven',
        description: 'A cozy retreat with vibrant colors, eclectic decor, and an inviting boho vibe.',
        imageUrl: '/images/bohemian-bedroom1.jpg',
        altText: 'A bedroom with comfy bed ,hanging indoor plants and beautiful wall paintings',
    },
    {
        id: 3,
        roomType: 'Kitchen',
        designStyle: 'Rustic',
        title: 'Warmth of the Countryside',
        description: 'A modern kitchen with rustic materials, farmhouse charm, and natural tones.',
        imageUrl: '/images/rustic-kitchen1.jpg',
        altText: 'A kitchen with wooden decor and fresh white tulips on the table',
    },
    {
        id: 4,
        roomType: 'Living Room',
        designStyle: 'Rustic',
        title: 'Earthy Elegance',
        description: 'A rich and textured space blending natural tones with rugged charm.',
        imageUrl: '/images/rustic-living-room1.jpg',
        altText: 'Living room with cane furniture and rustic walls',
    },
    {
        id: 5,
        roomType: 'Living Room',
        designStyle: 'Bohemian',
        title: 'A Touch of Wanderlust',
        description: 'Bring global vibes home with lush greenery, vibrant textures, and eclectic decor.',
        imageUrl: '/images/bohemian-living-room1.jpg',
        altText: 'A living room with cane furniture, cactus and macrame hanging on wall',
    },
    {
        id: 6,
        roomType: 'Bedroom',
        designStyle: 'Minimalist',
        title: 'Light-Filled Minimalism',
        description: 'A serene retreat with soft light, clean lines, and neutral colors for ultimate relaxation.',
        imageUrl: '/images/minimalist-bedroom1.jpg',
        altText: 'Bedroom with white aesthetics, a lamp on the table and palm plant in the corner',
    },
    {
        id: 7,
        roomType: 'Bedroom',
        designStyle: 'Minimalist',
        title: 'Neutral Simplicity',
        description: 'Elegance in simplicity, this bedroom pairs neutral tones with minimalist furniture.',
        imageUrl: '/images/minimalist-bedroom2.jpg',
        altText: 'Bedroom with white aesthetics, fresh white curtains and a plant next to the bed',
    },
    {
        id: 8,
        roomType: 'Bedroom',
        designStyle: 'Minimalist',
        title: 'Timeless Minimalist Retreat',
        description: 'An elegantly simple minimalist bedroom with soft tones and ornate headboard details.',
        imageUrl: '/images/minimalist-bedroom3.jpg',
        altText: 'A white-walled bedroom with a scenic window view',
    },
    {
        id: 9,
        roomType: 'Kitchen',
        designStyle: 'Bohemian',
        title: 'Charming Bohemian Kitchen',
        description: 'A vibrant and artistic kitchen with eclectic decor, open shelving, and a cozy ambiance, perfect for culinary creativity.',
        imageUrl: '/images/bohemian-kitchen1.jpg',
        altText: 'A kitchen with kitchen island and white decorated wallpaper',
    },
    {
        id: 10,
        roomType: 'Kitchen',
        designStyle: 'Minimalist',
        title: 'Modern Minimalist Kitchen',
        description: 'A sleek and organized kitchen featuring clean lines, neutral tones, ' +
                    'and a harmonious blend of modern design and functionality.',
        imageUrl: '/images/minimalist-kitchen1.jpg',
        altText: 'A kitchen with white cabinets and a refrigerator at the corner',
    },
    {
        id: 11,
        roomType: 'Living Room',
        designStyle: 'Minimalist',
        title: 'Elevated Living Charm',
        description: 'A serene space featuring natural wood accents, soft textures, and abundant natural light for a welcoming ambiance.',
        imageUrl: '/images/minimalist-living-room2.jpg',
        altText: 'A living room with cane furniture, cactus and macrame hanging on wall',
    },
];

export default inspirations;